name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Или master, в зависимости от вашей ветки

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build with env vars
        env:
          VUE_APP_API_BASE_URL: ${{ secrets.VUE_APP_API_BASE_URL }}
          VUE_APP_ROOT_URL: ${{ secrets.VUE_APP_ROOT_URL }}
          VUE_APP_API_TIMEOUT: 5000
          VUE_APP_DEBUG: false
          NODE_ENV: production
        run: |
          echo "VUE_APP_API_BASE_URL=$VUE_APP_API_BASE_URL" >> .env.production
          echo "VUE_APP_ROOT_URL=$VUE_APP_ROOT_URL" >> .env.production
          echo "VUE_APP_API_TIMEOUT=$VUE_APP_API_TIMEOUT" >> .env.production
          echo "VUE_APP_DEBUG=$VUE_APP_DEBUG" >> .env.production
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist